import { db } from '@/lib/db'
import { NextResponse } from 'next/server'

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url)
    const caseId = searchParams.get('caseId')

    if (!caseId) {
      return NextResponse.json({ error: 'caseId is required' }, { status: 400 })
    }

    const caseData = await db.case.findUnique({
      where: { id: caseId },
      include: {
        requirements: { orderBy: { sortOrder: 'asc' } },
        counselingSessions: { orderBy: { date: 'desc' } },
        drugTests: { orderBy: { date: 'desc' } },
        naSteps: { orderBy: { stepNumber: 'asc' } },
        naMeetings: { orderBy: { date: 'desc' } },
        supervisedVisits: { orderBy: { date: 'desc' } },
        courtDates: { orderBy: { date: 'desc' } },
        parentingClasses: { orderBy: { date: 'desc' } },
        milestones: { orderBy: { targetDate: 'asc' } },
        dailyCheckIns: { orderBy: { date: 'desc' } },
      },
    })

    if (!caseData) {
      return NextResponse.json({ error: 'Case not found' }, { status: 404 })
    }

    const fd = (d: Date | null) => d ? new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : 'N/A'

    const c = caseData
    const s = {
      completedRequirements: c.requirements.filter(r => r.isCompleted).length,
      totalRequirements: c.requirements.length,
      negativeDrugTests: c.drugTests.filter(t => t.result === 'negative').length,
      totalDrugTests: c.drugTests.filter(t => t.result).length,
      completedNASteps: c.naSteps.filter(s2 => s2.isCompleted).length,
      totalCounselingSessions: c.counselingSessions.filter(s2 => s2.isCompleted).length,
      completedVisits: c.supervisedVisits.filter(v => v.isCompleted).length,
      completedMilestones: c.milestones.filter(m => m.isCompleted).length,
    }

    let body = `REUNIFY PROGRESS REPORT\n========================\n\n`
    body += `Case Number: ${c.caseNumber}\n`
    body += `Court: ${c.courtName || 'N/A'}\n`
    body += `Caseworker: ${c.caseworkerName || 'N/A'}\n`
    body += `Judge: ${c.judgeName || 'N/A'}\n`
    body += `Attorney: ${c.attorneyName || 'N/A'}\n`
    body += `Case Status: ${c.caseStatus || 'Active'}\n`
    body += `Removal Date: ${fd(c.removalDate)}\n`
    body += `Target Reunification: ${fd(c.targetReunificationDate)}\n\n`

    body += `COMPLIANCE SUMMARY\n------------------\n`
    body += `Requirements: ${s.completedRequirements}/${s.totalRequirements} completed\n`
    body += `Drug Tests: ${s.negativeDrugTests}/${s.totalDrugTests} clean\n`
    body += `NA Steps: ${s.completedNASteps}/12 completed\n`
    body += `Counseling Sessions: ${s.totalCounselingSessions} attended\n`
    body += `Supervised Visits: ${s.completedVisits} completed\n`
    body += `Milestones: ${s.completedMilestones} achieved\n\n`

    if (c.drugTests.length > 0) {
      body += `DRUG TEST RESULTS\n-----------------\n`
      c.drugTests.forEach(t => {
        body += `${fd(t.date)} — ${t.testType || 'Test'} — Result: ${t.result || 'Pending'}\n`
      })
      body += `\n`
    }

    if (c.naMeetings.length > 0) {
      body += `NA/AA MEETINGS\n--------------\n`
      c.naMeetings.forEach(m => {
        body += `${fd(m.date)} — ${m.meetingName || 'Meeting'} at ${m.location || 'N/A'} — Verified: ${m.isVerified ? 'Yes' : 'No'}\n`
      })
      body += `\n`
    }

    if (c.parentingClasses.length > 0) {
      body += `PARENTING CLASSES\n-----------------\n`
      c.parentingClasses.forEach(p => {
        body += `${fd(p.date)} — ${p.className || 'Class'} — ${p.isCompleted ? 'Completed' : 'Upcoming'}${p.hasCertificate ? ' (Certificate)' : ''}\n`
      })
      body += `\n`
    }

    body += `Report generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}\n`
    body += `Generated by Reunify — CPS Reunification Progress Tracker\n`

    const subject = `Reunify Case Progress Report — ${c.caseNumber}`

    return NextResponse.json({ subject, body })
  } catch (error) {
    console.error('Error generating email body:', error)
    return NextResponse.json({ error: 'Failed to generate email body' }, { status: 500 })
  }
}
